<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2023-12-13 13:53:22
 */
return [
    'all' => [
        'class' => 'frontend\\assets\\AppAsset',
        'basePath' => '@webroot/',
        'baseUrl' => '@web/',
        'jsOptions' => [
            'defer' => 'defer',
        ],
        'js' => [
            'assets/all-e9b998e844c00cce1c82aba989b1bbcb.min.js',
        ],
        'css' => [
            'assets/all-69c31352ec5f249c55159b30d05c2d09.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\assets\\NpmAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'frontend\\assets\\FancyboxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\NpmAsset',
            'frontend\\assets\\FancyboxAsset',
            'all',
        ],
    ],
];